[package]
description = "Generic transaction pool."
name = "transaction-pool"
version = "1.13.3"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"

[dependencies]
error-chain = "0.12"
log = "0.4"
smallvec = "0.6"
trace-time = { path = "../trace-time", version = "0.1" }

[dev-dependencies]
ethereum-types = "0.4"
