[package]
name = "plain_hasher"
description = "Hasher for 32-bit keys."
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
keywords = ["hash", "hasher"]
homepage = "https://github.com/paritytech/parity-common"
categories = [ "no-std"]

[dependencies]
crunchy = "0.1.6"

[features]
default = ["std"]
std = []