language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build
  - cargo test --all --exclude uint
  - cd uint/ && cargo test --features=std,impl_quickcheck_arbitrary
