[package]
name = "libsecp256k1"
version = "0.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"
description = "Renaming crate for libsecp256k1."
license = "GPL-3.0"

[dependencies]
libsecp256k1 = { version = "0.1" }
