[package]
description = "Large fixed-size integers arithmetics"
homepage = "http://parity.io"
repository = "https://github.com/paritytech/primitives"
license = "MIT/Apache-2.0"
name = "uint"
version = "0.2.2"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[dependencies]
byteorder = { version = "1", default-features = false }
heapsize = { version = "0.4.2", optional = true }
rustc-hex = { version = "1.0", optional = true }
quickcheck = { version = "0.6", optional = true }

[dev-dependencies]
crunchy = "0.1.5"
quickcheck = "0.6"

[features]
std = ["rustc-hex", "byteorder/std"]
heapsizeof = ["heapsize"]
use_asm = []
impl_quickcheck_arbitrary = ["quickcheck"]

[[example]]
name = "modular"
required-features = ["std"]
