[package]
name = "keccak-hasher"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Keccak-256 implementation of the Hasher trait"
repository = "https://github.com/paritytech/parity/"
license = "GPL-3.0"

[dependencies]
ethereum-types = "0.4"
tiny-keccak = "1.4.2"
hashdb = { version = "0.3.0", path = "../../hashdb" }
plain_hasher = {  path = "../../plain_hasher" }
