[package]
name = "keccak-hash"
version = "0.1.2"
description = "`keccak-hash` is a set of utility functions to facilitate working with Keccak hashes (256/512 bits long)."
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
# ethereum-types = "0.4" TODO revert when published
ethereum-types = { path = "../../parity-primitives/ethereum-types" }
tiny-keccak = "1.4"

[dev-dependencies]
tempdir = "0.3"
