[package]
name = "parity-crypto"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethereum-types = "0.3"
quick-error = "1.2.2"
ring = "0.12"
tiny-keccak = "1.4"
scrypt = "0.1.1"
ripemd160 = "0.7.0"
digest = "0.7"
aes = "0.2.0"
aes-ctr = "0.1.0"
block-modes = "0.1.0"
block-cipher-trait = "0.5.3"

[features]
rustCrypto = []
default = ["rustCrypto"]
