[package]
name = "parity-crypto"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"
description = "Crypto utils used by ethstore and network."
license = "GPL-3.0"
autobenches = false

[[bench]]
name = "bench"
harness = false


[dependencies]
quick-error = "1.2.2"

tiny-keccak = "1.4"
scrypt = { version = "0.1.1", default-features = false }
ripemd160 = "0.8.0"
sha2 = "0.8.0"
digest = "0.8"
aes = "0.3.2"
aes-ctr = "0.3.0"
block-modes = "0.2.0"
lazy_static = "1.0" # for secp
mem = { path = "../mem" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ring = "0.13"
eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1" }
arrayvec = "0.4" # needed for eth-secp256k1
rand = "0.4"
hmac = { version = "0.7", optional = true }
libsecp256k1 = { path = "./libsecp256k1", optional = true }
pbkdf2 = { version = "0.3", default-features = false, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
hmac = "0.7"
subtle = { version = "1.0" }
# libsecp256k1 = { version = "0.1", package = "libsecp256k1" } // requires 'rename-dependency' in stable
libsecp256k1 = { path = "./libsecp256k1" }
rand = "0.5"
pbkdf2 = { version = "0.3", default-features = false }

[dev-dependencies]
hmac = "0.7"
# libsecp256k1 = { version = "0.1", package = "libsecp256k1" } // requires 'rename-dependency' in stable
libsecp256k1 = { path = "./libsecp256k1" }
pbkdf2 = { version = "0.3", default-features = false }
criterion = "0.2"

[features]
# expose alternative wasm32 implementation for testing and benchmarks
alt = ["hmac", "libsecp256k1", "pbkdf2"]
nightly = ["subtle/nightly"]
volatile-erase = ["mem/volatile-erase"]
