[package]
name = "triehash"
version = "0.5.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "In-memory patricia trie operations"
repository = "https://github.com/paritytech/parity-common"
license = "GPL-3.0"

[dependencies]
hash-db = { version = "0.12.3", default-features = false, features = ["std"] }
rlp = { version = "0.4", path = "../rlp" }

[dev-dependencies]
keccak-hasher = "0.12.3"
tiny-keccak = "1.4.2"
ethereum-types = { version = "0.7", path = "../ethereum-types" }
hex-literal = "0.2"
