[package]
name = "triehash"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "In-memory patricia trie operations"
repository = "https://github.com/paritytech/parity-common"
license = "GPL-3.0"

[dependencies]
hashdb = { version = "0.3.0", path = "../hashdb", default-features = false }
rlp = { version = "0.3.0", path = "../rlp", default-features = false }

[dev-dependencies]
trie-standardmap = { version = "0.1", path = "../trie-standardmap" }
keccak-hasher = { version = "0.1", path = "../test-support/keccak-hasher" }
tiny-keccak = "1.4.2"
#ethereum-types = "0.5"
ethereum-types = { path = "../../parity-primitives/ethereum-types" }

[features]
ethereum = ["rlp/ethereum"]
